name: Act Test
on: [workflow_dispatch, push]

jobs:
  test-simple:
    name: Simple Test
    runs-on: ubuntu-latest
    container:
      image: elixir:1.15.8
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
      
      - name: Check format
        run: mix format --check-formatted
      
      - name: Compile
        run: mix compile --warnings-as-errors