name: Local CI Test
on: [workflow_dispatch, push, pull_request]

jobs:
  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # OpenSSLのインストール
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libncurses5-dev
      
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.8'
          otp-version: '25.3'
      
      - name: Install mix dependencies
        run: |
          mix deps.get
      
      - name: Check format
        run: mix format --check-formatted

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: yesql_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libncurses5-dev
      
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.8'
          otp-version: '25.3'
      
      - name: Install mix dependencies
        run: |
          mix deps.get
          mix compile
      
      - name: Run tests
        env:
          MIX_ENV: test
          POSTGRES_HOST: localhost
        run: |
          mix ecto.create
          mix ecto.migrate
          mix test