# act用のローカルテストワークフロー
# 使用方法: act -W .act/workflows/test.yml

name: Local Test
on: [push]

jobs:
  test-simple:
    name: Simple Test
    runs-on: ubuntu-latest
    container:
      image: elixir:1.15.8
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
      
      - name: Check format
        run: mix format --check-formatted
      
      - name: Compile
        run: mix compile --warnings-as-errors

  test-with-postgres:
    name: Test with PostgreSQL
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: yesql_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.8'
          otp-version: '25.3'
      
      - name: Install dependencies
        run: |
          mix deps.get
          mix compile
      
      - name: Run tests
        env:
          MIX_ENV: test
          POSTGRES_HOST: postgres
        run: |
          mix ecto.create
          mix ecto.migrate
          mix test